name: Build Test and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly on Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Fix lightningcss for Linux
      run: |
        npm uninstall lightningcss
        npm install lightningcss@1.22.0 --platform=linux --arch=x64
      
    - name: Lint
      run: npm run lint

    - name: Build
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LIGHTNINGCSS_SKIP_NATIVE_TARGETS: 1
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-output
        path: .next
        retention-days: 5

  deploy:
    name: Deploy to Firebase
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .next
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Setup Cloud Functions
        working-directory: ./functions
        run: npm ci
      
      - name: Build Cloud Functions
        working-directory: ./functions
        run: npm run build
      
      # Set up GCP authentication instead of using Firebase token
      - name: Setup GCP Authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      
      - name: Deploy to Firebase
        run: firebase deploy --only functions,hosting --project mpch-458204 --non-interactive
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}