name: Build and Deploy MCP Server to Cloud Run

on:
  push:
    branches: [master, feat/add-nx-build]
    paths:
      - "mcp/**"
      - "lib/**"
      - "services/**"
      - "shared/**"
      - "app/types/**"
      - ".github/workflows/deploy-mcp-to-cloud-run.yml"
      - "nx.json"
      - "tsconfig.base.json"
      - "Dockerfile.mcp"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev --quiet
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.IMAGE_NAME }}:latest -f Dockerfile.mcp .
          docker push ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.IMAGE_NAME }}:latest
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.RUN_SERVICE_NAME }} \
            --image ${{ secrets.ARTIFACT_REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.IMAGE_NAME }}:latest \
            --region ${{ secrets.REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},REGION=${{ secrets.REGION }},VERTEXAI_EMBEDDING_MODEL=${{ secrets.VERTEXAI_EMBEDDING_MODEL }},GCS_BUCKET_NAME=${{ secrets.GCS_BUCKET_NAME }},GCS_DEFAULT_BUCKET_LOCATION=${{ secrets.GCS_DEFAULT_BUCKET_LOCATION }}"
